spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/momp?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/momp?gssapiServiceName=mongodb
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876

momp:
  elasticsearch:
    host: 127.0.0.1
    port: 9200