spring:
  datasource:
    url: jdbc:mysql://192.168.6.54:3306/momp?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://192.168.6.54:27017/momp?gssapiServiceName=mongodb
  redis:
    host: 192.168.6.54
    port: 6379
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.6.54:9876

momp:
  elasticsearch:
    host: 192.168.6.54
    port: 9200
